### ISSUE TITLE
Allow to hold for scroll in the pattern and instrument docks

### ISSUE THREAD

**Issue by YuriSizov** [YuriSizov/boscaceoil-blue#19]
Currently, you have to click the previous/next arrow button for every scroll step, which can become annoying quickly. Especially in patterns, of which we can have dozens, hundreds even.

A system to hold for scroll, with acceleration, should be added, similar to scrolling in the pattern and arrangement editors.

**Comment by darkhog** [comment]
#15 would also help with scroll in a more intuitive way.

**Comment by YuriSizov** [comment]
#15 is unrelated to the docks, though. We can actually use normal scroll wheel in them for scrolling, without any modifier keys, since there is no conflicting behavior.

I'm also reluctant to implement your suggestion for the arrangement and pattern editors, because I don't like the idea that the scroll wheel by default does something unexpected and you need a modifier key to trigger its normal behavior.
