### ISSUE TITLE
Blurred texts with Gui Scale 75% on Linux Mint 21.3 and 1080p monitor 1920x1080

### ISSUE THREAD

**Issue by TheMelancholyOfGigi198** [YuriSizov/boscaceoil-blue#26]
The texts are blurred, you can notice much more above all if the gui scale decreases (in my case to 75%)

Bosca Ceoil Blue
![2024-07-14_13-33](https://github.com/user-attachments/assets/58c51a25-b5ac-42ff-ba04-12ca1b28d677)

Old ver.
![2024-07-14_13-33_1](https://github.com/user-attachments/assets/8f4dbc55-09cd-4177-84dd-fdb4b416b7e2)

Maybe a fix for this problem could be removed the "Billinear" filter from the various texts

**Comment by YuriSizov** [comment]
Yes, blurriness at smaller scales is a known issue. Unfortunately, I couldn't find a working solution for scales below 100% in Godot. I will probably have to rework entire UI to be rendered natively at a smallest scale and then scale it up for everything else, which seems to work fine.

**Comment by YuriSizov** [comment]
Actually, there might be a way that I've missed. If it works, I'll try to release the next update sooner than originally planned.

**Comment by YuriSizov** [comment]
This should be addressed in 3.1 by 579ea859e2c1765d6cacae2aaed866afa432562a. In short, your native scale for 1080p should be 100% now, as the app is rendered at a smaller size, appropriate for standard DPI screens and FullHD resolutions. This removes the need to downscale in your case and thus removes the issues with blurriness!

When 3.1 is out you will have to update the settings to use the 100% scale as your existing settings will still be respected and the app will become tiny. If for some reason it's too small to be usable, open your user folder and look for `boscaceoil-blue`, with `bosca.settings` inside. It's a text file and you can edit it to change the GUI scale back to 100%. Or you can delete and at let the app generate a new one, resetting all the settings to default.

(See [this](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#accessing-persistent-user-data-user) for the place where your user folder is for your operating system.)
