### ISSUE TITLE
Drumkit note editor not aligning with labels

### ISSUE THREAD

**Issue by Exposure849** [YuriSizov/boscaceoil-blue#35]
This issue wasn't there at install. I think it may have begun after decreasing the GUI scale to 50% but I'm really not sure.
This misalignment doesn't happen to other instruments.

v3.0 stable
Windows 64bit

https://github.com/user-attachments/assets/802a37aa-d2f5-4672-b990-636f89cddbd8

**Comment by YuriSizov** [comment]
Hey, thanks for the report! This is Windows 10, right?

**Comment by Exposure849** [comment]
Yes, this is Windows 10. However, I realized I'm only having this issue when loading a specific .ceol file. New songs and loading other .ceol files do not have the same issue, so I guess this can be closed. I've attached the file in case anyone wants to take a look ¯\_(ツ)_/¯
Thank you for the quick response!

[instruments.zip](https://github.com/user-attachments/files/16680669/instruments.zip)

**Comment by YuriSizov** [comment]
Ah, that's great to have! Before we close the issue, I'll see what's going on and how to fix this.

Say, when you mention "loading", do you mean this was made with a previous version of Bosca?

**Comment by Exposure849** [comment]
Nope, this file is from v3.0 stable.

**Comment by Disonantemus** [comment]
Same happens 2 me, maybe 4 playing with instruments like: `Simple DrumKit` that has fewer rows.
Using: [Last release 3.0-stable for Linux](https://github.com/YuriSizov/boscaceoil-blue/releases/download/3.0-stable/boscaceoil-blue-linux-x86_64.zip).

---

~~~ocaml
distro: Arch Linux x86_64
kernel: 6.6.22-1-lts
shell: bash 5.2.32
term: tmux
cpu: Intel i7-4790 (8) @ 3.600GHz
gpu: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
~~~
