### ISSUE TITLE
There's no hotkey to start from the beginning

### ISSUE THREAD

**Issue by AG-ZL** [YuriSizov/boscaceoil-blue#43]
this is a low priority issue

on original bosca, space is bound to the 'end' button, while the music is playing

please bind the end button to something

i lost all my pcs data and wanted to reinstall bosca and found this (very cool), the new control for space is the pause button instead of the end button. generally when i tweak the music i want to re-listen to what i changed so space being bound to restart was very good cuz it put me back at the start of the part i was listening to. also when i highlight the whole song i want to go from the start but when i press space the first few notes are skipped

i dont want you to worry about it saving whenever i load the programme since this is super specific and not very demanded.

i have uploaded an image to help those  who dont quite understand:
![this](https://github.com/user-attachments/assets/120ce1ef-8fec-49cd-92c0-63d32c8fe666)

if there is a hotkey to go from the top please make it clear, i did re-read the tutorial and mash my keyboard looking for it but its not there

**Comment by YuriSizov** [comment]
I agree, this change was not a great on my part. In 3.1 the <kbd>Spacebar</kbd> will work as it did in Bosca 2.x. The new behavior, if desired, will be accessible via <kbd>Ctrl + Spacebar</kbd>.
