### ISSUE TITLE
GUI and window scaling in general is wack.

### ISSUE THREAD

**Issue by PrismaNotTerra** [YuriSizov/boscaceoil-blue#50]
I am using a 1920x1080 monitor, with 100% Windows scale. However, unlike the original, this one not only starts as a massive window, but it can't be reduced to a reasonable size without changing the GUI scale to 50%, and all GUI scales result in text that does not respect pixels; It blurs the entire application, leading to everything being very eye-straining. This is probably just a me problem, so maybe a toggle that forces the program to be pixel-perfect could work, or it could be added as a GUI setting.

**Comment by YuriSizov** [comment]
Hey, thanks for the report! This is definitely not just you, and it has been reported before across various platform. E.g. https://github.com/YuriSizov/boscaceoil-blue/issues/26.

This is fixed in version 3.1, which I am currently working on and hope to release later this month.
