### ISSUE TITLE
nightly builds

### ISSUE THREAD

**Issue by DeanLemans** [YuriSizov/boscaceoil-blue#53]
a nightly version that builds every night.

reasoning:

i like having more up to date software

please close if to much effort

**Comment by YuriSizov** [comment]
Hey there!

I appreciate the idea, but I don't think I can justify official nightly builds. For starters, there isn't that much work going on on the project. It's mostly just me working on Bosca, and I don't do it continuously. My release cycle (so far) is:

- Dedicate a couple of months to work on multiple changes, 
- Release a few betas to help test the new version for stability,
- Build and publish the final stable release for the version.

Anything that I commit during the development stage cannot be considered stable and safe for you to use. There may be breaking changes which happen unexpectedly for any number of reasons, and commits may be incomplete. But, if you insist on using something that is potentially unstable, you can always use build artifacts from CI.

- Go to this page: https://github.com/YuriSizov/boscaceoil-blue/actions?query=branch%3Amain
- Click on any run from the list (sorted from most recent ones to the older ones)
- Scroll to the bottom to the "Artifacts" section
- Click on the build for your platform and download the archive

Note: if you're a Mac user then you must consider that these builds are not codesigned, and you may have issues running them on your device.

Ultimately, Bosca is not a rapidly developed piece of software, and there is no need to keep close tabs on it.
