### ISSUE TITLE
Random instruments sometimes mismatch name and instrument type

### ISSUE THREAD

**Issue by ugackMiner53** [YuriSizov/boscaceoil-blue#7]
When creating new instruments, the randomly selected instrument has a chance to "copy" the previous instrument into the instrument field, despite it being a different instrument. The correct instrument is played in the track and in the name field, but the correct instrument type is not shown. The reported type of the instrument is then changed based on the previous instrument selected. See attached Video for an example.

**Reproduction Steps**
1. Click "Create New Instrument"
2. Repeat previous step until name of instrument does not match selected instrument
3. Observe name changes depending on previous name 

This behavior is not present on the original Bosca Ceoil, in case you were curious!

https://github.com/YuriSizov/boscaceoil-blue/assets/55325485/166c9aaa-cf85-43c8-8de0-13d933daba69

<details><summary><b>Specific Details</b></summary>
<br>

Version: `3.0-beta1`
Downloaded: `
boscaceoil-blue-windows-x86_64.zip `
OS: `Windows 11 (Home) x86_64`
Kernel: `WIN32_NT 10.0.22631.3593 (23H2)`
Processor: `12th Gen Intel(R) Core(TM) i7-12700H (20) @ 4.70 GHz`
GPU: `NVIDIA GeForce RTX 3060 Laptop GPU (5.87 GiB)`
Memory: `16 GB`

</details>

**Comment by YuriSizov** [comment]
Oh, that's very curious! Thanks for the detailed report, I'll look into it

**Comment by YuriSizov** [comment]
That was a silly mistake on my part! This happens when the category stays the same as you select a different instrument. Should be fixed in beta 2, whenever that comes out.
